name: Update Submodule

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "Uyen Bui Huynh Kim"
          git config --global user.email "uyen.bhku@gmail.com"
          git config --global credential.helper store
          echo "machine github.com login your-username password your-personal-access-token" > ~/.netrc

      - name: Update submodule
        run: |
          git submodule update --init --recursive
          cd CS105.O21/demo
          git fetch origin main
          git checkout main
          cd ..
          git add .
          git commit -m "Update submodule to latest"
          git push --force origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
